### ISSUE TITLE
Error: 'manifest' is not a registered wp command

### ISSUE THREAD

**Issue by tedmasterweb** [runcommand/manifest#8]
*Summary*
executing `wp manifest` returns the error in the title.

*Preconditions*
* wp is at or above 0.24 (we're testing with version 1.0)
* manifest has been installed by executing `wp package install runcommand/manifest` (see Notes below for details)

*Steps to Reproduce*
1. Starting in the document root for the site, execute `wp manifest`

*Expected Result*
* A fantastic table with details about the site

*Actual Result*
* Error: 'manifest' is not a registered wp command

*Workaround*
(none)

*Notes*
When installing, the system returns the following output (yes, installing as root with the --allow-root switch)
```
Installing package runcommand/manifest (dev-master)
Updating /root/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
```

**Comment by tedmasterweb** [comment]
The test for the original report (above) was done on CentOS. I just tested on Mac OS X and got the following error:
```
Updating /Users/tedsr/.wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
<pre style='color: #ff0000'>
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in phar:///usr/local/bin/wp-cli.phar/vendor/composer/composer/src/Composer/DependencyResolver/Rule.php on line 60
```

HTH

**Comment by danielbachhuber** [comment]
> When installing, the system returns the following output (yes, installing as root with the `--allow-root switch)`

It looks like the installation process isn't completing here. The full output should be something like this:

```
wp package install runcommand/manifest
Installing package runcommand/manifest (dev-master)
Updating /Users/danielbachhuber/wp-cli/packages/composer.json to require the package...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 0.036 seconds
Analyzed 3417 packages to resolve dependencies
Analyzed 86902 rules to resolve dependencies
Package operations: 1 install, 1 update, 0 removals
Installs: runcommand/manifest:dev-master 073a747
Updates: wp-cli/admin-command:dev-master 58d842b
 - Installing runcommand/manifest (dev-master 073a747)
Writing lock file
Generating autoload files
---
Success: Package installed.
```

> The test for the original report (above) was done on CentOS. I just tested on Mac OS X and got the following error:

You'll need to increase available memory. Composer is a bit of a memory hog.

**Comment by tedmasterweb** [comment]
Bumped it up to 256 with no love, and then to 512 and everything worked fine. Thanks.
